# Generated by Django 4.1.5 on 2023-05-18 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resource', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_id', models.CharField(max_length=50)),
                ('assign_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Billable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_id', models.CharField(max_length=50)),
                ('bill_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='addBillable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Billed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assign.billable')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.details')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='addAssigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assign.assigned')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.details')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
