# Generated by Django 4.1.5 on 2023-05-20 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addbillable',
            name='Billed',
        ),
        migrations.DeleteModel(
            name='Billable',
        ),
    ]
