# Generated by Django 4.1.5 on 2023-05-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('start_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
